"""unique_email

Revision ID: 1a30a7f2137f
Revises: e0c1b12969d2
Create Date: 2022-09-08 13:11:34.552447

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1a30a7f2137f'
down_revision = 'e0c1b12969d2'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
