"""add_email

Revision ID: 909ef89e8963
Revises: 6427ddb05d65
Create Date: 2022-09-08 13:52:09.416849

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '909ef89e8963'
down_revision = '6427ddb05d65'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('email', sa.String(), nullable=False))
    op.create_unique_constraint(None, 'users', ['email'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_column('users', 'email')
    # ### end Alembic commands ###
